#!/bin/bash
#
# dmgr
#
# run stuff to prem a host
#

if [ ! -x /usr/sbin/chrony ]
then
  echo "Installing chrony"
  sudo apt install chrony
fi

grep microk8s /etc/group
if [ $? -eq 1 ]
then
  echo "Adding group microk8s"
  sudo groupadd -f microk8s
fi

grep microk8s /etc/group | grep labuser
if [ $? -eq 1 ]
then
  echo "Adding group microk8s to user labuser"
  sudo usermod -a -G microk8s labuser
  echo "Please logout and in again!!!"
  exit 1
fi

if [ ! -b /dev/sdb ]
then
  echo "No second disk - add second disk"
  exit 1
fi
