#!/bin/bash
#
# dmgr
#
# run stuff to prem a host
#

if [ ! -r $HOME/.vimrc ]
then
  echo "Adding .vimrc"
  cp vimrc $HOME/.vimrc
fi

if [ ! -x /usr/sbin/chronyd ]
then
  echo "Installing chrony"
  sudo apt -y install chrony
fi

if [ ! -x /usr/bin/expect ]
then
  echo "Installing expect"
  sudo apt -y install expect
fi

grep microk8s /etc/group >/dev/null
if [ $? -eq 1 ]
then
  echo "Adding group microk8s"
  sudo groupadd -f microk8s
fi

grep microk8s /etc/group | grep labuser >/dev/null
if [ $? -eq 1 ]
then
  echo "Adding group microk8s to user labuser"
  sudo usermod -a -G microk8s labuser
  echo "Please logout and in again!!!"
  exit 1
fi

if [ ! -b /dev/sdb ]
then
  echo "No second disk - add second disk"
  exit 1
fi

df -k | grep /backing_store >/dev/null
if [ $? -eq 1 ]
then
  echo "Formatting sdb"
  ./partition.exp
  uuid=`ls -l /dev/disk/by-partuuid | grep sdb1 | awk '{ print $9 }'`
  if [ "$uuid" = "" ]
  then
    echo "Cannot determine uuid of sdb"
    exit 2
  fi
  echo $uuid
  sudo mkfs -t ext4 /dev/disk/by-partuuid/$uuid
  sudo mkdir /backing_store
  sudo cp /etc/fstab /tmp/fstab
  sudo echo "/dev/disk/by-partuuid/$uuid /backing_store  ext4 defaults 0 2" >> /tmp/fstab
  sudo cp /tmp/fstab /etc/fstab
  sudo mount /backing_store
  sudo chown labuser:labuser /backing_store
fi

